SFEhtdig.spec:   patches/htdig-01-debian.diff:   Added jumbo patch from Debian Etch (several improvemements) with   further additions to fix Makefile issues causing undefined symbols   at runtime. patches/kdebase-01-startkde.diff:   Add /usr/openwin/bin to PATH to get X utilities(iceauth) on SXDE.
git-svn-id: https://pkgbuild.svn.sourceforge.net/svnroot/pkgbuild/spec-files-extra/trunk@855 3354ce84-6216-0410-ad3d-afc617165c18

diff --git a/patches/kdebase-01-startkde.diff b/patches/kdebase-01-startkde.diff
--- a/patches/kdebase-01-startkde.diff
+++ b/patches/kdebase-01-startkde.diff
@@ -1,12 +1,20 @@
---- kdebase-3.5.8/startkde.orig	2008-01-19 10:20:35.354977000 +0530
-+++ kdebase-3.5.8/startkde	2008-01-19 10:21:30.819083000 +0530
+--- kdebase-3.5.8/startkde.orig	2008-02-01 00:28:01.909106210 +0530
++++ kdebase-3.5.8/startkde	2008-02-01 00:28:48.643270864 +0530
 @@ -1,4 +1,4 @@
 -#!/bin/sh
 +#!/usr/bin/bash
  #
  #  DEFAULT KDE STARTUP SCRIPT ( KDE-3.5.8 )
  #
-@@ -377,7 +377,7 @@
+@@ -7,6 +7,7 @@
+ # because we still need to do some cleanup.
+ trap 'echo GOT SIGHUP' HUP
+ 
++PATH=${PATH}:/usr/sfw/bin:/usr/openwin/bin:/usr/X11/bin
+ # Check if a KDE session already is running
+ if kcheckrunning >/dev/null 2>&1; then
+ 	echo "KDE seems to be already running on this display."
+@@ -377,7 +378,7 @@
  fi
  
  # wait if there's any crashhandler shown
