2008-11-21  Brian Cameron  <brian.cameron@sun.com>
        * SFEsimplejson.spec: Bump to 2.0.4.
        * ext-sources/svc-gdm, ext-sources/gdm.xml:  Now use the method
          script for stopping the service.


git-svn-id: https://pkgbuild.svn.sourceforge.net/svnroot/pkgbuild/spec-files-extra/trunk@1519 3354ce84-6216-0410-ad3d-afc617165c18

diff --git a/ext-sources/svc-gdm b/ext-sources/svc-gdm
--- a/ext-sources/svc-gdm
+++ b/ext-sources/svc-gdm
@@ -11,19 +11,29 @@
 #
 # # svccfg
 # svc:> select application/graphical-login/gdm
-# svc:/application/graphical-login/gdm> setprop gdm/debug = "true"
 # svc:/application/graphical-login/gdm> exit
 
-FMRI=svc:application/graphical-login/gdm
+. /lib/svc/share/smf_include.sh
 
-debug=`svcprop -p gdm/debug $FMRI`
-
-arg=`eval "echo \`svcprop -p gdm/args $FMRI\`"`
-
-if [ $debug = "true" ]; then
-	/usr/sbin/gdm $arg --debug &
-else
+case "$1" in
+'start')
 	/usr/sbin/gdm $arg &
-fi
+	rc=$?
+
+	if [ $rc != 0 ]; then
+		echo "$0: gdm failed with $rc"
+		exit 1
+	fi
+	;;
+
+'stop')
+	/usr/sbin/gdm-stop
+	;;
+
+*)
+	echo "Usage: $0 { start | stop }"
+	exit 1
+	;;
+esac
 
 exit $SMF_EXIT_OK
